### PR TITLE
Integrate onboarding topic selections into PFAR diversification

### PR DESCRIPTION
**Pull request by karlhigley**
Companion PRs:
* https://github.com/CCRI-POPROX/poprox-concepts/pull/6
* https://github.com/CCRI-POPROX/poprox-platform/pull/78

This combines onboarding selections and the topics of clicked articles into a single topic distribution. The five-point scale presented during onboarding is adjusted so that the lowest interest level counts as zero clicks and the highest counts as four clicks, which are then summed with the topics from clicked articles and then normalized before being passed into the PFAR implementation.

### CODE REVIEW

**Comment by karlhigley** [comment]
(The tests won't pass until upstream PRs get merged)

**Review by mdekstrand — APPROVED** [review]
LGTM but also wouldn't mind seeing @imrecommender or @sophiasun0515's opinion since they know this bit of the code better.

**Comment by sophiasun0515** [comment]
LGTM as well, would love to see the `test_pfar.py` file also gets updated if possible, but we can improve that in a separate PR.

**Comment by mdekstrand** [comment]
Following up on our discussion in Slack, I have written #36 that adds reliable relocking support through a shell script that automates the correct `conda-lock` invocation. It is currently failing the Docker test, because of the `poprox-concepts` changes. The following steps should fix this PR:

1. merge #36
2. merge resulting new `main` into this PR branch
3. relock dependencies

**Comment by karlhigley** [comment]
@sophiasun0515 I've made minor updates to `test_pfar.py` here to integrate the shared list of high-level topics, but not done anything beyond that yet. I think some of the code that's currently in this repository around computing topic distributions should probably move into the platform and be provided "for free" to all recommender implementations, and I'm not sure how that will dovetail with `test_pfar.py` yet.

**Pull request merged**
