### PR TITLE
Update pfar test to be included in pytest suite

### PR DESCRIPTION
**Pull request by sophiasun0515**
Update dvc pull to include test data in git check workflow, and updated pfar test

### CODE REVIEW

**Comment by karlhigley** [comment]
@sophiasun0515 Looks like it needs some formatting tweaks to pass the pre-commit hook checks. If you've already done `pre-commit install` to set up the commit hooks, then you can run `git commit --amend --no-edit` to run them on the previous commit (since amend technically makes a new commit, which triggers the hooks again.)

**Comment by sophiasun0515** [comment]
> @sophiasun0515 Looks like it needs some formatting tweaks to pass the pre-commit hook checks. If you've already done `pre-commit install` to set up the commit hooks, then you can run `git commit --amend --no-edit` to run them on the previous commit (since amend technically makes a new commit, which triggers the hooks again.)

Thanks! I've run both commands and here's the output:
```
(poprox-recsys) sun00587@cs-u-jamjar:~/research/POPROX/poprox-recommender$ git commit --amend --no-edit
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/google/yamlfmt.
[INFO] Initializing environment for https://github.com/astral-sh/ruff-pre-commit.
[INFO] Initializing environment for local:@taplo/cli.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/google/yamlfmt.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/astral-sh/ruff-pre-commit.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
check for added large files..........................(no files to check)Skipped
check json...........................................(no files to check)Skipped
check for merge conflicts............................(no files to check)Skipped
check that scripts with shebangs are executable......(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
debug statements (python)............................(no files to check)Skipped
fix end of files.....................................(no files to check)Skipped
mixed line ending....................................(no files to check)Skipped
trim trailing whitespace.............................(no files to check)Skipped
format yaml files....................................(no files to check)Skipped
ruff.................................................(no files to check)Skipped
ruff-format..........................................(no files to check)Skipped
toml-format..........................................(no files to check)Skipped
[test/update-pfar-test 1e3517a] update pfar test to be included in pytest suite
 Date: Wed Jun 26 19:15:31 2024 +0000
 1 file changed, 23 insertions(+), 38 deletions(-)
```

But there's no changes I can push locally...now what should I do?

**Comment by karlhigley** [comment]
It looks like the tests do run `dvc pull` but only pull model files if I'm reading this right: https://github.com/CCRI-POPROX/poprox-recommender/blob/main/.github/workflows/run-tests.yml#L48

I suspect the reason for that is to avoid pulling the whole MIND dataset, but maybe we can figure out how to edit that line to pull test files too?

**Comment by karlhigley** [comment]
> But there's no changes I can push locally...now what should I do?

Looks like that didn't actually work! Another approach would be to `git reset HEAD~1` (go back one commit but keep the changes) and then make a new commit

**Comment by sophiasun0515** [comment]
> > But there's no changes I can push locally...now what should I do?
> 
> Looks like that didn't actually work! Another approach would be to `git reset HEAD~1` (go back one commit but keep the changes) and then make a new commit

Sounds good, I'll reset and see if I can find a way to modify the `run-tests.yml` file so we can make it pass here as well!

**Comment by karlhigley** [comment]
It should run these checks and auto-format the code before each commit normally, so hopefully you won't need these sneaky tricks to re-trigger the hooks again in the future (but they're still handy to know on occasion.)

**Comment by karlhigley** [comment]
I updated the workflow file on the `main` branch to include the `tests` directory in the `dvc pull`, but it looks like that doesn't take effect in branches unless the change in included in the branch too. I think merging `main` into your branch will be enough, and that might make the tests pass.

**Comment by sophiasun0515** [comment]
> I updated the workflow file on the `main` branch to include the `tests` directory in the `dvc pull`, but it looks like that doesn't take effect in branches unless the change in included in the branch too. I think merging `main` into your branch will be enough, and that might make the tests pass.

I rebased on main and push again, but looks like it's still failing 😆 Lemme see what else we can do here

**Comment by karlhigley** [comment]
Looks like the tests passed, so I think it's just the formatting now

**Review by karlhigley — APPROVED** [review]

**Pull request merged**
